### PR TITLE
appveyor remove integration test from build

### PR DESCRIPTION
**Pull request by klokane**
* backport appveyor from master
* remove integration test from build on appveyor

@pksunkara please merge, one more

### CODE REVIEW

**Comment by klokane** [comment]
hmm looks some problem on appveyor

**Comment by pksunkara** [comment]
Failing.

**Comment by klokane** [comment]
Hmm looks, `perf  test` require cmdline, which I remove remove earlier from project :(

**Comment by pksunkara** [comment]
Are you sure? `test/perf-snowcrash.cc` only uses `snowcrash::parse` from `src/snowcrash.h`

**Comment by klokane** [comment]
Yes, it is reason why build fail 

see: https://ci.appveyor.com/project/Apiary/snowcrash/build/1.0.5#L153

https://github.com/apiaryio/snowcrash/blob/shared/mson-integration/test/performance/perf-snowcrash.cc#L12

**Comment by pksunkara** [comment]
Ah, you mean the `cmdline` submodule. I thought you meant the snowcrash cmdline.

**Comment by klokane** [comment]
Fixed

**Pull request merged**
