### PR TITLE
Implemented parsing of inline action

### PR DESCRIPTION
**Pull request by pksunkara**
Serialisation will be done in apiaryio/drafter.

### CODE REVIEW

**Comment by pksunkara** [comment]
Appveyor is stupid. :angry:

**Comment by zdne** [comment]
> Appveyor is stupid. :angry:

It is not, it is looking for MSVC solution file. Which we do not have by default. Needs to be changed to use `vcbuild.bat`

**Comment by klokane** [comment]
Seem good. I mean there shoud be added unit test for  `MatchAction`  functor

**Comment by pksunkara** [comment]
Updated.

**Comment by kylef** [comment]
I know this has already been merged, but there seems to be a bug. Take the following example, when linting it uses the wrong uriTemplate for actions:

```bash
$ cat test2.md
FORMAT: 1A

## Users [/users]

### Create [POST]

+ Response 204

### Add a friend [POST /users/{username}/friends/{friend}]

+ Parameters
    + username
    + friend

+ Response 204

$ ./bin/snowcrash -lu test2.md

OK.
warning: (8)  parameter 'username' not specified in 'Users' its '/users' URI template; line 9, column 1 - line 10, column 1
warning: (8)  parameter 'friend' not specified in 'Users' its '/users' URI template; line 9, column 1 - line 10, column 1
```

/cc @pksunkara

**Comment by zdne** [comment]
good catch @kylef !

**Pull request merged**
