### PR TITLE
Remove unused code

### PR DESCRIPTION
**Pull request by goganchic**
This code is doing nothing useful, I think it's some kind of legacy.

### CODE REVIEW

**Comment by pksunkara** [comment]
I am not sure about that unused code part. But redundant check can probably be removed.

**Comment by kylef** [comment]
The repository is now merged into Drafter itself so changes should be made their instead of this repository.

https://github.com/apiaryio/drafter/tree/master/ext/snowcrash

**Comment by goganchic** [comment]
@pksunkara why are you in doubt about unused code? You can't be in this function if current node isn't `Attributes`, so imho it's unnecessary to make this check again.

**Comment by goganchic** [comment]
@kylef ok, I'll change PR to that repository.

**Pull request closed without merging**
