### PR TITLE
chore: Remove SC_API

### PR DESCRIPTION
**Pull request by pksunkara**

### CODE REVIEW

**Comment by klokane** [comment]
Why we remove this?
I think we may get into troubles on protagonist build. 
Did you check it?

**Comment by pksunkara** [comment]
It doesn't exist in the repo anymore since we removed C snowcrash API.

**Comment by klokane** [comment]
`snowcrash::parse()` is isn't exported for dll?

**Comment by pksunkara** [comment]
Nope. It doesn't need any prefix currently

**Comment by klokane** [comment]
ok

**Comment by w-vi** [comment]
drafter.js will be affected : https://github.com/apiaryio/drafter.js/blob/master/src/cparse.h#L8

But drafter.js will set it up for itself, it will be cleaner anyway.

**Pull request merged**
