### PR TITLE
[sundown] Don't include headings within list items

### LINKED ISSUE #322: Crash while parsing malformed blueprint
Parsing following blueprint results in crash: 

```markdown
## GET /a

+ Response 200

            a
>           b
            e
# B
```

```
Assertion failed: (0), function src_map_location, file ../drafter/ext/snowcrash/ext/markdown-parser/ext/sundown/src/src_map.c, line 158.
Abort trap: 6
```

Note:  The error is most likely caused in our `sundown` module, but due to lack of the test there it should be tested a tracked in Snow Crash.

### PR DESCRIPTION
**Pull request by kylef**
A heading cannot be inside a list item.

Dependent PRs:

- [x] https://github.com/apiaryio/sundown/pull/9
- [x] https://github.com/apiaryio/markdown-parser/pull/11 I can update reference to master once dependent PRs are merged.

Fixes #322

### CODE REVIEW

**Comment by zdne** [comment]
Waiting for update on apiaryio/sundown#9

**Comment by pksunkara** [comment]
I have checked for any regressions which I was afraid we might have due to the changes in the parser. Everything is okay. But I cannot merge this yet, because the behaviour of the parser in the two conceptually similar test cases is quite different.

##### Normal header style

The header node is outside the block quote node.

```
+ root (type 0, data 0) - `` :0:59
  + header (type 4, data 1) - `GET /a` :0:10
  + list item (type 6, data 10) - `` :10:46
    + paragraph (type 7, data 0) - `Response 200` :12:14
    + code (type 1, data 0) - `a
` :30:6
    + quote (type 2, data 0) - `` :36:16
      + code (type 1, data 0) - `  b
e
` :38:14
  + header (type 4, data 1) - `B` :56:3
```

##### Setext header style

The header node is inside the block quote.

```
+ root (type 0, data 0) - `` :0:72
  + header (type 4, data 1) - `GET /a` :0:10
  + list item (type 6, data 2) - `` :10:62
    + paragraph (type 7, data 0) - `Response 200` :12:14
    + code (type 1, data 0) - `a
` :30:6
    + quote (type 2, data 0) - `` :36:16;50:16
      + code (type 1, data 0) - `  b
e
` :38:14
      + header (type 4, data 2) - `Heading` :52:16
```

**Comment by zdne** [comment]
@pksunkara seems like the limitation of the parser. I wonder if we need to worry about settext headers at all. Thoughts?

**Comment by pksunkara** [comment]
We do not know if some people are using setext headers. I will leave the decision to you to merge this PR or let kyle fix it.

**Comment by zdne** [comment]
@pksunkara what was the behavior before this PR? Is this a regression?

**Comment by pksunkara** [comment]
I checked this and it is behaving the same above before this PR fix. So, I am merging this now.

**Pull request merged**
