### PR TITLE
Removed cli and serialization from Xcode targets

### PR DESCRIPTION
**Pull request by pksunkara**
I cleaned up a bit of Xcode configuration after the recent removal of cli, c-interface and serialization from snowcrash.

### CODE REVIEW

**Comment by zdne** [comment]
@pksunkara no mention on changes in ModelTable. This feels like trafficking other changes with it. Please try to separate concerns next time (or at least elaborate in PR description).

**Comment by pksunkara** [comment]
The changes in ModelTable are related to Xcode since they are under `DEBUG`. Those changes are nothing but making sure that removal of `sos` as dependency doesn't effect anything in `DEBUG`.

**Comment by klokane** [comment]
I'm not able to check Xcode, I'm on vim :) @zdne can you merge, please?

**Comment by zdne** [comment]
> The changes in ModelTable are related to Xcode since they are under DEBUG. Those changes are nothing but making sure that removal of sos as dependency doesn't effect anything in DEBUG.

@pksunkara so please mention it next time, this is not apparent from the content of PR nor its description

**Pull request merged**
