### PR TITLE
fix capture groups count

### PR DESCRIPTION
**Pull request by goganchic**

### CODE REVIEW

**Comment by kylef** [comment]
This looks good to me.

@pksunkara do you know if there is any reason why the count of the capture groups is +1?

**Comment by pksunkara** [comment]
I honestly don't remember. It might be something to do with Action/Resource ambiguity. I am sorry to be thinking here "If it ain't broke, don't fix it".

**Comment by pksunkara** [comment]
@goganchic Do you have a failing test with the current code?

**Comment by goganchic** [comment]
I don't have failing tests now.

**Comment by pksunkara** [comment]
We have moved away the code for snowcrash to drafter

**Pull request closed without merging**
